<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\shared\connectionStrings.Development.json" Link="Configs\connectionStrings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>

    <Content Include="..\..\shared\connectionStrings.Production.json" Link="Configs\connectionStrings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentMigrator" Version="5.0.0" />
    <PackageReference Include="FluentMigrator.Runner" Version="5.0.0" />
    <PackageReference Include="FluentMigrator.Runner.SQLite" Version="5.0.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>


</Project>
