<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\shared\connectionStrings.Development.json" Link="Configs\connectionStrings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>

    <Content Include="..\..\shared\connectionStrings.Production.json" Link="Configs\connectionStrings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>

    <Content Include="..\..\docs\Протокол осмотра места происшествия.docx" Link="templates\Протокол осмотра места происшествия.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSService.Blazor\CSService.Blazor.csproj" />
    <ProjectReference Include="..\CSService.Queries\CSService.Queries.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

</Project>
